pacosTacos/apps/Login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^register$', views.register, name='register'),
	url(r'^login$', views.login, name='login'),
	url(r'^success$', views.success, name='success')
]

pacosTacos/apps/Taco/urls.py
from django.conf.urls import url 
from . import views

app_name='taco'
urlpatterns = [
	url(r'^$', views.home, name='home')
]

pacosTacos/pacosTacos/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.Login.urls', namespace='login')),
    url(r'^taco', include('apps.Taco.urls', namespace='taco'))
]

pacosTacos/apps/Login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import bcrypt
import re
from django.db import models

# Create your models here.

class UserManager(models.Manager):
	def registerUser(self, postData):
		results = {'status': True, 'errors': [], 'user': None}
		if not postData['name'] or len(postData['name']) < 3:
			results['status'] = False
			results['errors'].append('Enter and name that is more than 3 characters in length')
		if not postData['username'] or len(postData['username']) < 3:
			results['status'] = False
			results['errors'].append('Username must be more than 3 characters')
		if not re.match(r'(^[a-zA_Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)', postData['email']):
			results['status'] = False
			results['errors'].append('INVALID EMAIL!!!!!!!!')
		if not postData['password'] or len(postData['password']) < 8:
			results['status'] = False
			results['errors'].append('Password must be more than 8 characters')
		if postData['confPassword'] != postData['password']:
			results['status'] = False
			results['errors'].append('Passwords do not match')

		if results['status'] is False:
			return results
		user = User.objects.filter(email=postData['email'])

		if user:
			results['status'] = False
			results['errors'].append('Failed to register new User')
		if results['status']:
			hashPass = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
			user = User.objects.create(
				name=postData['name'],
				username=postData['username'],
				email=postData['email'],
				password=hashPass)
			user.save()
			results['user'] = user
		return results

	def loginUser(self, postData):
		results = {'status': True, 'errors': [], 'uesr': None}
		user = User.objects.filter(email=postData['email'])
		try:
			user[0]
		except IndexError:
			results['status'] = False
			results['errors'].append('None of this is correct. I give up Just Leave')
			return results
		if user[0]:
			if user[0].password != bcrypt.hashpw(postData['hashPass'].encode(), user[0].password.encode()):
				results['status'] = False
				results['errors'].append('Everything has failed. Everybody Panic and Run!!!!!!!')
			else:
				results['user'] = user[0].id
		else:
			results['status'] = False
		return results

class User(models.Model):
	name = models.CharField(max_length=100)
	username = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=100)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	objects = UserManager()

pacosTacos/apps/Taco/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

pacosTacos/apps/Login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import  User

# Create your views here.
def index(request):
	print '**Login Index**' * 250
	return render(request, 'Login/index.html')

def register(request):
	print '**Register User**' * 250
	results = User.objects.registerUser(request.POST)
	if not results['status']:
		for error in reults['errors']:
			messages.error(request, error)
		return redirect('login:index')
	request.session['id'] = reults['user'].id
	return redirect('login:success')


def login(request):
	print '**Login User**' * 250
	results = User.objects.loginUser(request.POST)
	if not results['status']:
		for error in results['errors']:
			messages.error(request, error)
		return redirect('login:index')
	request.session['id'] = results['user'].id
	return redirect('login:success')

def success(request):
	# user = User.objects.get(id=request.session.get('id'))
	# contents = {
	# 	'user': user
	# }
	return redirect('taco:home')

pacosTacos/apps/Taco/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from ..Login.models import User

# Create your views here.
def home(request):
	user = User.objects.get(id=request.session.get('id'))
	contents = {
		'user': user
	}
	render(request, 'Taco/taco.html', contents)

pacosTacos/apps/Login/templates/Login/index.html
<html>
<head>
	<meta charset="UTF-8">
	<title>Pacos Tacos</title>
</head>
<body>
	<h1>Pacos Tacos</h1>
	<h3>The Best Friend Finder based on Tacos</h3>
	<p>Find yourself with a lack of friends?</p>
	<p>We can help fill that void in your life. Here at Pacos Tacos with specialize in matching you with your perfect friend based on our taco-based algorithm. Let us help season up your life</p>
	<h2>Register New User</h2>
	<form action="{% url 'login:register' %}" method="POST">
		{% csrf_token %}
		<label for="name">Name: </label>
		<input type="text" name="name">
		<label for="username">Username: </label>
		<input type="text" name="username">
		<label for="email">Email: </label>
		<input type="text" name="email">
		<label for="password">Password: </label>
		<input type="password" name="password">
		<label for="confPassword">Confirm Password: </label>
		<input type="password" name="confPassword">
		<input type="submit" name="register" value="Register!">
	</form>
	<h2>Returning User</h2>
	<form action="{% url 'login:login' %}" method="POST">
		{% csrf_token %}
		<label for="email">Email: </label>
		<input type="text" name="email" >
		<label for="password">Password: </label>
		<input type="password" name="password">
		<input type="submit" name="login" value="Login!">
	</form>
</body>
</html>